title: jikt.im
description: Stupid people writing stupid articles about stupid things.
permalink: /blog/:year/:title/
url: https://jikt.im
logo: /assets/img/logo.png

collections:
  - members

markdown: kramdown
highlighter: rouge

twitter:
  username: jiktim_
  card: summary

socials:
  github: jiktim
  twitter: jiktim_
  twitter_domain: jikt.im

compress_html:
  comments: all

exclude:
  - .editorconfig
  - .eslintrc
  - .gitignore
  - .gitattributes
  - .prettierrc
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

kramdown:
  auto_ids: false
  input: GFM

paginate: 10
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-target-blank
